### ISSUE TITLE
session_not_on_or_before returns None

### ISSUE THREAD

**Issue by Glocktober** [HENNGE/minisaml#15]
response.py  pulls session_not_on_or_before from SessionNotOnOrBefore of the saml:AuthnStatement... 
but I don't find that in an Azure AD XML response.

    <AuthnStatement AuthnInstant="2021-08-06T14:10:54.000Z"
                    SessionIndex="_ed453acb-45bc-4cb3-96ee-8dcb477ebe01">
      <AuthnContext>
        <AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</AuthnContextClassRef>
      </AuthnContext>
    </AuthnStatement>

It does exist as 'NotOnOrBefore' in both SubjectConfirmationData and Conditions leafs:

      <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <SubjectConfirmationData InResponseTo="idM0ZwS_AjxD2jd0Hv"
                                 NotOnOrAfter="2021-08-06T21:45:02.030Z"
                                 Recipient="http://localhost:8000/saml/acs" />
      </SubjectConfirmation>
    </Subject>
    <Conditions NotBefore="2021-08-06T20:40:02.030Z"
                NotOnOrAfter="2021-08-06T21:45:02.030Z">
      <AudienceRestriction>
        <Audience>URN:test1</Audience>
      </AudienceRestriction>
    </Conditions>

I'm not sure if this is an implementation to implementation thing, or if the standard defines where this would be. I would think the 'Conditions' section is more correct, and the response.py code already verifies these.

Is it possible to provide those as part of what validate_response() returns?

Attaching a sanitized xml segment from Azure

[x.xml.txt](https://github.com/HENNGE/minisaml/files/6948000/x.xml.txt)

**Comment by ojii** [comment]
> response.py pulls session_not_on_or_before from SessionNotOnOrBefore of the saml:AuthnStatement...
> but I don't find that in an Azure AD XML response.

`SessionNotOnOrBefore` is optional in SAML, so it's entirely normal for some IdPs not to provide one ([SAML Core, Section 2.7.1.](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf))}. The meaning of this field is for the IdP to give a hint to the SP that the SP should not issue a session that lasts longer than the provided time. 

`Conditions` and its `NotBefore`/`NotOnOrAfter` restrict the period of validity of the SAML Assertion but is unrelated to the duration of the session that an SP issues ([SAML Core, Section 2.5.1.2](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf)). These are optional according to the spec, but minisaml treats assertions without these attributes as invalid for security reasons. 

The `NotOnOrAfter on `SubjectConfirmationData` serves a similar purpose to the one on `Conditions` ([SAML Core, Section 2.4.1.2](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf)) and must fall within the period specified by the attributes on `Conditions`. This attribute is currently not checked by minisaml and probably should be.

So, the reason why minisaml returns `session_not_on_or_before` is because this is potentially useful to the user of this library, as it lets your restrict the length of the session you issue on your SP to within the time period specified by the SAML Response. The attributes on `Conditions`/`SubjectConfirmationData` are not returned since they are only used to check if the SAML Response/Assertion is actually valid.

**Comment by dimaqq** [comment]
If I read the above right, the Azure response means "issue the user a session for as long as you want". 🤔

**Comment by ojii** [comment]
> If I read the above right, the Azure response means "issue the user a session for as long as you want". 🤔

correct.

**Comment by Glocktober** [comment]
I guess I'm not understanding this.

If the assertions are asserted on 'condition' of NotOnOrAfter xxx date, then what difference does it make when the SSO session with the IdP expires?

I don't think an IdP would issue assertions beyond their own (idp) session expiration.

i.e. if the assertions are expired by the 'condition', the web session is defacto expired, and shouldn't proceed using the assertions.  The SP should initiate another SAMLRequest at that point, which is exactly why I want the Conditions NotOnOrAfter.

currently I set my code to 3600 because I know that's what Azure and AWS provide conditions, but it would be more elegant if I could pull it from the minisaml response.

**Comment by dimaqq** [comment]
> I don't think an IdP would issue assertions beyond their own (idp) session expiration.

1. well it's an assumption
2. they could issue assertions much shorter then their own session expiration, what then?

**Comment by ojii** [comment]
> I guess I'm not understanding this.
> 
> If the assertions are asserted on 'condition' of NotOnOrAfter xxx date, then what difference does it make when the SSO session with the IdP expires?
> 
> I don't think an IdP would issue assertions beyond their own (idp) session expiration.
> 
> i.e. if the assertions are expired by the 'condition', the web session (my SP session) is defacto expired, and shouldn't proceed using the assertions. The SP should initiate another SAMLRequest at that point, which is exactly why I want the Conditions NotOnOrAfter.
> 
> currently I set my code to 3600 because I know that's what Azure and AWS provide conditions, but it would be more elegant if I could pull it from the minisaml response.

`NotOnOrAfter` on `Condition` is not related to session duration in either the IdP or the SP. It's strictly related to when the SAML Assertion should be considered valid. This is so SAML Assertions cannot be endlessly re-used. Without `NotOnOrAfter` you could intercept a (valid) SAML Assertion once, and then just use that one forever when you try to authenticate, without ever involving the IdP again. 

`SessionNotOnOrAfter` is a hint from the IdP, (strongly) suggesting to the SP it should not issue a valid session beyond that time.

**Comment by Glocktober** [comment]
> I don't think an IdP would issue assertions beyond their own (idp) session expiration
> 1. well it's an assumption
If the IdP considers the session expired then it's not in a position to make any *assertions* on that data.

> 2. they could issue assertions much shorter then their own session expiration, what then?
Generally the assertions ARE  far shorter than the  (IdP) session.   
When they do expire you initiate a new SAMLRequest and refresh the assertions from the SAMLResponse.
I do this manually now by expiring the users assertions every hour
Expiring the SAML Assertions based on the Conditions NotOnOrAfter  allows DS updates to group memberships, roles, other changes in user data etc. to propagate to the SP in a more timely fashion.
The IdP session remains valid even if the assertions change - you get the updated assertions without the IdP requiring you to reauthenticate (i.e. by waiting for the Session NotOnOrAfter.).
What I'm asking for is that you provide the Conditions notOnOrAfter on the verified response object.  That way I can use that to refresh SAML attributes.
I do it now every 3600 Seconds, but it would seem better to honor the IdP's conditions.


    On Wednesday, August 11, 2021, 10:43:50 PM EDT, Dima Tisnek ***@***.***> wrote:  
 
 



I don't think an IdP would issue assertions beyond their own (idp) session expiration.

   
   - well it's an assumption
   - they could issue assertions much shorter then their own session expiration, what then?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dimaqq** [comment]
> Assertions based on the Conditions NotOnOrAfter allows DS updates to group memberships, roles, other changes in user data etc. to propagate to the SP

🤔  I don't think this feature was considered when this library was originally written.

Frankly, this is beyond my scope, and I don't quite understand how this would work in practice — my 2c: in the common use case, the end user will continue using the service until the service auth expires and only then will be redirected to the idp or will visit the idp directly triggering new saml that may contain updated assertion. In my simplistic view: long service sessions — happy users; short service sessions — timely updates. Thus each service needs to define (make configurable) the length of the service session, as a limit to, or perhaps even regardless of the idp.

I'll leave this discussion and proposal to @ojii 

P.S. pull requests are always welcome!

**Comment by ojii** [comment]
> Generally the assertions ARE  far shorter than the  (IdP) session. 

They can often be very short (note, we run an IdP and our default NotOnOrAfter is 11 minutes in the future). 

> When they do expire you initiate a new SAMLRequest and refresh the assertions from the SAMLResponse.

You don't have to do that though (if you have any claim to the contrary, please link them to me). This library implements (a subset of) the Web SSO Profile of SAML, where the SP can use the assertion to create their own security context (aka a session). The SP is free to have that context have a longer timespan than the assertion, based on the needs of the SP.

> I do this manually now by expiring the users assertions every hour Expiring the SAML Assertions based on the Conditions NotOnOrAfter  allows DS updates to group memberships, roles, other changes in user data etc. to propagate to the SP in a more timely fashion. 

If your SP requires frequent assertions to keep these values up-to-date, then you're free to issue sessions of whatever duration your SP deems appropriate. Following NotOnOrAfter here doesn't seem useful to me, as an IdP might issue more distant NotOnOrAfter values and then your goal of keeping those values in sync would not be met.

> The IdP session remains valid even if the assertions change - you get the updated assertions without the IdP requiring you to reauthenticate (i.e. by waiting for the Session NotOnOrAfter.). 

But this comes at a cost (at the very least an HTTP roundtrip to the IdP), so again, it's up to the SP to decide how often this should be done.

> What I'm asking for is that you provide the Conditions notOnOrAfter on the verified response object.  That way I can use that to refresh SAML attributes. I do it now every 3600 Seconds, but it would seem better to honor the IdP's conditions.

I think choosing your own refresh period is actually better. If 1 hour makes sense for your SP, then use 1 hour. 

A major goal of this library is to keep the surface are light and clear. Having two (optional) expiration dates on the response would be confusing, as this whole discussion shows that NotOnOrAfter and SessionNotOnOrAfter are not immediately clear. 

Because of this, I will not include NotOnOrAfter in the Response object.
